apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes: {{ .Values.pvc.accessModes }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}